### ISSUE TITLE
MPIConsumer finalization crash

### ISSUE THREAD

**Issue by Jonas-Wessner** [gemfony/geneva#28]
MPIConsumer crashes with segfault at end of program:

backtrace:

(gdb) backtrace
#0  0x00007fffef9a6acf in raise () from /lib64/libc.so.6
#1  0x00007fffef979ea5 in abort () from /lib64/libc.so.6
#2  0x00007fffef9e7cd7 in __libc_message () from /lib64/libc.so.6
#3  0x00007fffef9eefdc in malloc_printerr () from /lib64/libc.so.6
#4  0x00007fffef9efa44 in malloc_consolidate () from /lib64/libc.so.6
#5  0x00007fffef9f1090 in _int_free () from /lib64/libc.so.6
#6  0x00007fffdf6aca3f in kh_destroy_vfs_obj_inplace (h=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>)
    at vfs/base/vfs_obj.c:79
#7  ucs_initializer_dtor0 () at vfs/base/vfs_obj.c:825
#8  0x00007ffff7dd6cee in _dl_fini () at dl-fini.c:141
#9  0x00007fffef9a926c in __run_exit_handlers () from /lib64/libc.so.6
#10 0x00007fffef9a93a0 in exit () from /lib64/libc.so.6
#11 0x00007fffef992d8c in __libc_start_main () from /lib64/libc.so.6
#12 0x00000000005219be in _start ()

**Comment by Jonas-Wessner** [comment]
the problem has been identified and documented in issue #29
